### ISSUE TITLE
Lack of CSS nesting support makes “aside” and code blocks unreadable in dark mode on older browsers

### ISSUE THREAD

**Issue by adamwight** [blakewatson/htmlforpeople#1]
Absolutely brilliant book so far and I’m looking forward to reading and sharing!

I found that my wonky mobile browser (DDG 7.139.1.0) fails to set the dark background color on `aside`, so white text becomes invisible.  Screenshot attached.
![187804D6-B3C1-4D2C-BAD1-4F3DAF4000D1](https://github.com/user-attachments/assets/0c520862-6dd4-4208-9108-502b7f6cb065)

**Comment by adamwight** [comment]
DDG is WebKit, in my case equivalent to "safari 15.8" because I literally use phones from the dumpster.  caniuse reports that CSS nesting and the `&` selector don't become available until safari 16.4 .

I have a workaround of reading in light mode, and I don't want to challenge the wisdom in your decision to use vanilla CSS from the future.  Mostly, the site degrades gracefully but you might look into alternative base styling which ensures basic readability even with worse-case browsers.

---

On a side note, I also noticed a lot of redundant nesting selectors, if I'm understanding the syntax correctly.  For example,
```
A {
  & B { ... }
}
```

should be equivalent to
```
A {
  B { ... }
}
```

I think the only reason to use `&` explicitly is in special cases where the simpler syntax is impossible or awkward, such as `&.B` or `B &`

**Comment by adamwight** [comment]
The original issue is fixed, but I’ve found something similar happens on the next chapter, with code examples:
![A64084B6-B06D-4701-BF66-FA2AE311ED0B](https://github.com/user-attachments/assets/b03e9666-3d83-42aa-91be-78b8b47263c6)

**Comment by adamwight** [comment]
> I think the only reason to use `&` explicitly is in special cases where the simpler syntax is impossible or awkward, such as `&.B` or `B &`

Please ignore my comments about the redundant `&`.  I educated myself a bit more about the new syntax and [MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting) explain that the result is the same, but the extra symbol can be helpful as a hint to humans:
> As a visual indicator to aid with readability, when seeing the & nesting selector you know that CSS nesting is being used.

**Comment by adamwight** [comment]
Here are screenshots of the degraded condition on my older browser, with both patches applied.  It’s not quite as fancy, but it becomes usable.

![58B76DBF-E6EB-4863-B681-CAED163E1AF6](https://github.com/user-attachments/assets/a02aea20-bdfe-49c4-aa2b-b9a78bfd3626)
![87D78E7D-26A4-43F7-88CA-EDD91AC4F389](https://github.com/user-attachments/assets/50eb42d9-64f2-437c-ac47-faca5bfd8fd5)

**Comment by blakewatson** [comment]
I think for a time there, the `&` was needed because nested children needed to begin with a symbol. It seems like that's no longer the case. But either way, I think I might just unnest most of the styles.

https://webkit.org/blog/13813/try-css-nesting-today-in-safari-technology-preview/

![CleanShot 2024-10-11 at 01 20 30@2x](https://github.com/user-attachments/assets/6018cf66-9f7e-42bb-9257-3410b246286d)

**Comment by adamwight** [comment]
Unfortunate because the nesting makes the CSS so much nicer, but +1 to going either way with this.  I feel sheepish about complaining about problems with my fossil browser, but to be fair iOS 15 is not quite EOL yet, so I suppose it's still relevant.  OTOH, the [stats](https://gs.statcounter.com/) are showing that iOS 15 has less than 1% user share.  If you add this to eg. Chrome <= 111 however and the other older browsers, it might start to add up (very quick napkin math gives something like 9% might have no support for CSS nesting and 3% more might have sketchy partial support), especially considering that your book is geared towards non-specialists :relaxed: — I feel like the compromise of ensuring basic readability will be good enough in any case.

Thanks for considering these fixes!
