### ISSUE TITLE
Spanish Translation for Your Book

### ISSUE THREAD

**Issue by paulmelero** [blakewatson/htmlforpeople#7]
Have you considered creating a Spanish translation of your book?

I have experience translating technical content into Spanish and would love to help.

Here’s an example of my previous work:

English: [Testing Vue.js Components with Jest](https://leanpub.com/testingvuejscomponentswithjest)
Spanish: [Testeando Componentes de Vue.js con Jest](https://leanpub.com/testeando-vuejs/) 

If you're interested, we could discuss the possibility of splitting commissions from the translated version.

Looking forward to hearing from you!

Best regards,

Paul

**Comment by blakewatson** [comment]
I appreciate the idea but this is a free book. I do have a donation link but it doesn’t make enough to pay for a translation. Closing this for now.

**Comment by paulmelero** [comment]
I understand. Thank you for your response.
