### ISSUE TITLE
meta charset should probably be put before title

### ISSUE THREAD

**Issue by teddybradford** [blakewatson/htmlforpeople#8]
See: https://stackoverflow.com/a/30682871

Found `title` before `meta charset` in this section: https://htmlforpeople.com/add-content-to-your-website/#give-your-website-a-head-and-a-body

**Comment by blakewatson** [comment]
Thanks @teddybradford! Fixed it with https://github.com/blakewatson/htmlforpeople/commit/a62b1d3620eb814ab9d5ef4a5d1735dab85fc869.
